### PR TITLE
Migrate to GitHub Actions

### LINKED ISSUE #29: Use github actions instead of travis

### PR DESCRIPTION
**Pull request by adlerjohn**
Fixes #29

### CODE REVIEW

**Comment by liamsi** [comment]
Changes look good but it doesn't seem to trigger the action?

**Comment by adlerjohn** [comment]
1. Are Actions enabled for this repo?
2. Maybe Actions don't get triggered when they're first enabled by a PR from a fork?

**Comment by liamsi** [comment]
@musalbas can you make sure github actions is enabled for this repo?

**Review by liamsi — APPROVED** [review]
let's see if this only doesn't trigger bc it's from a fork 🤔

**Comment by liamsi** [comment]
looking good:
image

**Pull request merged**
