### PR TITLE
Test with leopard in CI

### PR DESCRIPTION
**Pull request by adlerjohn**
Run CI tests with `-tags leopard`.

Note: had to remove `arm64` as a build target since cgo doesn't work with cross-compiling.

### CODE REVIEW

**Comment by liamsi** [comment]
We don't see if this actually worked bc there is no diff in any go file. Do you mind changing CI to temporarily run even if there was no diff? I'm a bit surprised that only the build tag is necessary. On the other hand, we'd already see any issues regarding leopard during build-time I think.

**Comment by adlerjohn** [comment]
Hmm. I forget, were there any steps for installing `libleopard`?

**Comment by liamsi** [comment]
OK, now we see that this didn't work: 

```
# github.com/lazyledger/go-leopard/leopard
/usr/bin/ld: cannot find -llibleopard
/usr/bin/ld: cannot find -llibleopard
/usr/bin/ld: cannot find -llibleopard
/usr/bin/ld: cannot find -llibleopard
collect2: error: ld returned 1 exit status
FAIL	github.com/lazyledger/rsmt2d [build failed]
```

Currently, you'd need to add a few lines to actually build leopard and install it properly. Maybe this should be done in a Makefile. That way it would be a single line in the CI config and it could be re-used for other purposes, too.

**Comment by liamsi** [comment]
https://github.com/lazyledger/go-leopard/blob/50ec4b3fab41cd3af5adc88a3447f265acf59352/Makefile#L14-L20

**Comment by liamsi** [comment]
Should we merge this in first? I mean before #44 ?

**Comment by adlerjohn** [comment]
> Should we merge this in first?

Probably not, we'd want to get the CI actually installing `libleopard` and stuff first before testing with it so that it actually works. Converted to draft while I fix this. #44 is independent.

**Review by liamsi — COMMENTED** [review]
lgtm 👍🏼

**Review by liamsi — APPROVED** [review]
👍🏼

**Pull request merged**
